### ISSUE TITLE
parameterize on sun height at horizon

### ISSUE THREAD

**Issue by joeyh** [intractable/horizon#5]
It can be useful to know when the sun is centered on the horizon, or when it is completely behind the horizon, or when it has completely cleared the horizon. For example, I may want to know when to go out to enjoy a sunset, or I may want to know when to expect first light hitting solar panels.

The -0.83 in the code is tuning for the sun's upper limb touching the horizon. So that could be parameterized one way or other. I have a list of some common values, but it seems it sometimes needs to be corrected for altitude so perhaps exposing the parameter would be best.

**Comment by joeyh** [comment]
https://github.com/intractable/horizon/pull/1 implements this

**Comment by intractable** [comment]
Merged #1 / #9
